-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.32-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for db3749273_thuisbijdekat
CREATE DATABASE IF NOT EXISTS `db3749273_thuisbijdekat` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;
USE `db3749273_thuisbijdekat`;

-- Dumping structure for table db3749273_thuisbijdekat.customer
CREATE TABLE IF NOT EXISTS `customer` (
  `id` int(25) NOT NULL AUTO_INCREMENT,
  `address_id` int(25) NOT NULL,
  `alt_address_id` int(25) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `fname` varchar(34) NOT NULL,
  `lname` varchar(34) NOT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `verified` tinyint(1) DEFAULT 0,
  `verify_code` char(150) DEFAULT NULL,
  `password_lost` char(150) DEFAULT NULL,
  `attempts` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `address_id` (`address_id`),
  CONSTRAINT `customer_ibfk_1` FOREIGN KEY (`address_id`) REFERENCES `adres` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table db3749273_thuisbijdekat.customer: ~1 rows (approximately)
INSERT INTO `customer` (`id`, `address_id`, `alt_address_id`, `email`, `fname`, `lname`, `password_hash`, `verified`, `verify_code`, `password_lost`, `attempts`) VALUES
	(1, 98070, NULL, 'mauricemol@hotmail.nl', 'Maurice', 'Mol', '$2y$10$O7fGSyOYv9CgTFa9So66be7BFaHzb1v1jJ5EVeuMw/iygzFyGRPem', 0, '2bf9442053bd04a4ede368101bba039ee756df40de135926ad442a33fe7633b6', NULL, 0);

-- Dumping structure for table db3749273_thuisbijdekat.image
CREATE TABLE IF NOT EXISTS `image` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `path` varchar(500) NOT NULL,
  `type` varchar(5) NOT NULL,
  `alt` varchar(100) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1090 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table db3749273_thuisbijdekat.image: ~453 rows (approximately)
INSERT INTO `image` (`id`, `path`, `type`, `alt`) VALUES
	(1, 'Huushinne-productfotografie-lantaarn-8380.jpg', 'jpg', 'servies'),
	(6, 'Huushinne-productfotografie-lantaarn-8368.jpg', 'jpg', ''),
	(8, 'Huushinne-productfotografie-lantaarn-8348.jpg', 'jpg', ''),
	(9, 'Huushinne-productfotografie-lantaarn-8348.jpg', 'jpg', ''),
	(10, 'Huushinne-productfotografie-lantaarn-8348.jpg', 'jpg', ''),
	(12, 'Huushinne-productfotografie-lantaarn-8345.jpg', 'jpg', ''),
	(16, 'Huushinne-productfotografie-lantaarn-8346.jpg', 'jpg', ''),
	(18, 'Huushinne-productfotografie-lantaarn-8345.jpg', 'jpg', ''),
	(21, 'Productfoto\'s 22-09-2021-046.jpg', 'jpg', 'verzorging'),
	(24, 'Huushinne-productfotografie-lantaarn-8345.jpg', 'jpg', ''),
	(27, 'Huushinne-productfotografie-lantaarn-8345.jpg', 'jpg', ''),
	(30, 'Productfoto\'s 11-11-2021-170.jpg', 'jpg', ''),
	(35, 'Productfoto\'s 11-11-2021-170.jpg', 'jpg', ''),
	(38, 'Productfoto\'s 11-11-2021-159.jpg', 'jpg', 'tafellamp hkliving'),
	(39, 'paaseieren2.jpg', 'jpg', 'woonaccessoires'),
	(43, 'Product-fotos-09-02-2022-241-1-768x1152.jpg', 'jpg', 'hanglamp pitriet'),
	(45, '23-02-2022-6121.jpg', 'jpg', ''),
	(46, 'Woonspullen 16-02-2022-5992.jpg', 'jpg', ''),
	(47, '23-02-2022-6157.jpg', 'jpg', ''),
	(48, '23-02-2022-6127.jpg', 'jpg', 'lampen'),
	(50, '23-02-2022-6139.jpg', 'jpg', 'tag'),
	(51, '23-02-2022-6182.jpg', 'jpg', ''),
	(53, 'Woonspullen 16-02-2022-6023.jpg', 'jpg', 'wonen'),
	(54, '23-02-2022-6100.jpg', 'jpg', ''),
	(55, '23-02-2022-6097.jpg', 'jpg', ''),
	(56, '23-02-2022-6107.jpg', 'jpg', 'kleding'),
	(62, 'Huushinne 02-03-2022-6289.jpg', 'jpg', ''),
	(65, 'Huushinne 02-03-2022-6289.jpg', 'jpg', 'hanglamp,lampionlamp,linnen'),
	(66, 'Huushinne 02-03-2022-6292.jpg', 'jpg', 'hanglamp,lampionlamp,linnen'),
	(67, 'Huushinne-02-03-2022-6303.jpg', 'jpg', 'plaid-woonplaid'),
	(68, 'Huushinne-02-03-2022-6303.jpg', 'jpg', 'plaid-woonplaid'),
	(69, 'Huushinne-02-03-2022-6303.jpg', 'jpg', 'plaid-woonplaid'),
	(70, 'Huushinne-02-03-2022-6303.jpg', 'jpg', 'plaid-woonplaid'),
	(72, 'Huushinne 02-03-2022-6315.jpg', 'jpg', 'plaid De Weldaad'),
	(93, '23-02-2022-6205.jpg', 'jpg', ''),
	(98, '23-02-2022-6214.jpg', 'jpg', ''),
	(104, '23-02-2022-6117.jpg', 'jpg', ''),
	(114, '23-02-2022-6197.jpg', 'jpg', ''),
	(115, '23-02-2022-6197.jpg', 'jpg', ''),
	(116, '23-02-2022-6193.jpg', 'jpg', ''),
	(125, '23-02-2022-6134.jpg', 'jpg', ''),
	(128, '23-02-2022-6126.jpg', 'jpg', 'kussen,malagoon,wol'),
	(129, '23-02-2022-6136.jpg', 'jpg', 'kussen,wol,malagoon'),
	(132, '23-02-2022-6160.jpg', 'jpg', 'kussen,AAI made with love'),
	(134, '23-02-2022-6184.jpg', 'jpg', ''),
	(139, 'Product foto\'s 09-02-2022-250.jpg', 'jpg', 'lamp pitriet'),
	(141, '23-02-2022-6100.jpg', 'jpg', ''),
	(143, '23-02-2022-6097.jpg', 'jpg', ''),
	(144, 'Huushinne 06-04-2022-6544.jpg', 'jpg', 'kandelaars huushinne'),
	(145, 'plaid cheyenne zwart wit.jpg', 'jpg', ' Plaid cheyenne zwart wit'),
	(146, 'plaid cheyenne zwart wit.jpg', 'jpg', 'plaid cheyenne zwart wit'),
	(147, 'plaid cheyenne zwart wit.jpg', 'jpg', 'plaid zwart wit'),
	(152, 'Plaid HKliving wit .jpg', 'jpg', 'plaid wit HKLIVING'),
	(153, 'Plaid HKliving wit .jpg', 'jpg', ''),
	(154, 'Plaid HKliving wit .jpg', 'jpg', 'plaid,wit,hkliving'),
	(155, 'plaid hkliving wit.jpg', 'jpg', 'plaid,hkliving,wit'),
	(173, 'Huushinne-02-02-2022-5741.jpg', 'jpg', 'meubels'),
	(174, 'Huushinne 06-04-2022-6564.jpg', 'jpg', 'manden'),
	(175, '04-05-2022-7423.jpg', 'jpg', 'herdermessen'),
	(176, 'Woonspullen 16-02-2022-5973.jpg', 'jpg', 'nicolas vahÃ©,kruiden,peper,zout'),
	(177, 'Woonspullen 16-02-2022-5963.jpg', 'jpg', 'koken,pannen,BAF'),
	(178, 'Woonspullen 16-02-2022-6010.jpg', 'jpg', 'koksmessen,'),
	(179, 'HKLiving-januari-2022-5585.jpg', 'jpg', 'hkliving'),
	(180, '23-02-2022-6196.jpg', 'jpg', 'malagoon kussens'),
	(181, '04-05-2022-7421.jpg', 'jpg', 'mijn stijl'),
	(182, 'Huushinne 06-04-2022-6569.jpg', 'jpg', 'housholdhardware'),
	(183, 'Woonspullen 16-02-2022-6012.jpg', 'jpg', 'broste copenhagen'),
	(184, 'Huushinne 13-04-2022-6674.jpg', 'jpg', 'Simple'),
	(185, 'Kleding 09-02-2022-5863.jpg', 'jpg', 'european culture'),
	(186, 'Huushinne 13-04-2022-6683.jpg', 'jpg', 'beautiful story'),
	(187, 'kleding 23-02-2022-6231.jpg', 'jpg', 'kinderkleding'),
	(188, 'Huushinne 30-03-2022-6477.jpg', 'jpg', 'nicolas vahe'),
	(191, 'Huushinne 11-05-2022-8860.jpg', 'jpg', 'kussen,hkliving'),
	(192, 'Huushinne 11-05-2022-8861.jpg', 'jpg', 'kussen,hkliving'),
	(197, 'Huushinne 11-05-2022-8871.jpg', 'jpg', ''),
	(199, 'Huushinne 11-05-2022-8885.jpg', 'jpg', ''),
	(204, 'Huushinne 11-05-2022-8878.jpg', 'jpg', ''),
	(205, '23-02-2022-6130.jpg', 'jpg', 'kussen,antraciet,wol,malagoon'),
	(206, 'Huushinne 30-03-2022-6478.jpg', 'jpg', ''),
	(207, 'Product foto\'s 09-02-2022-265.jpg', 'jpg', 'egg chair'),
	(209, 'Huushinne-02-02-2022-5741.jpg', 'jpg', 'hocker  householdhardware'),
	(210, 'Huushinne-02-02-2022-5741.jpg', 'jpg', 'hocker, householdhardware'),
	(211, 'Huushinne-02-02-2022-5743.jpg', 'jpg', 'hocker  householdhardware'),
	(218, 'Huushinne 02-03-2022-6285.jpg', 'jpg', ''),
	(219, 'Huushinne 02-03-2022-6285.jpg', 'jpg', 'lampionlamp,linnen,hamgla,p'),
	(220, 'Huushinne 02-03-2022-6283.jpg', 'jpg', 'lampionlamp,linnen,hanglamp'),
	(221, 'Huushinne 02-03-2022-6279.jpg', 'jpg', ''),
	(224, 'Huushinne 02-03-2022-6277.jpg', 'jpg', 'hanglamp,lampionlamp,wit'),
	(225, 'Huushinne 02-03-2022-6279.jpg', 'jpg', 'hanglamp,lampionlamp,wit'),
	(226, 'Huushinne 02-03-2022-6297.jpg', 'jpg', 'lampionlamp.hanglamp,katoen'),
	(227, 'Huushinne 02-03-2022-6295.jpg', 'jpg', 'lampionlamp.hanglamp,katoen'),
	(228, 'Huushinne 30-03-2022-6466.jpg', 'jpg', ''),
	(229, 'Huushinne 30-03-2022-6466.jpg', 'jpg', 'mand bamboe'),
	(232, 'Huushinne 06-04-2022-65530.jpg', 'jpg', 'kussen, kussens, linnen kussen'),
	(233, 'Huushinne 25-05-2022-009.jpg', 'jpg', 'kussen, kussens, linnen kussen'),
	(235, '04-05-2022-74420.jpg', 'jpg', 'plaid beige blokken hkliving'),
	(240, 'sfeerfoto\'s-18-11-2021-27830.jpg', 'jpg', ''),
	(243, 'Huushinne 30-03-2022-6440.jpg', 'jpg', 'mand zeegras'),
	(246, 'Huushinne 25-05-2022-020.jpg', 'jpg', 'hanglamp,lampionlamp,bruin'),
	(247, 'Product foto\'s 09-02-2022-270.jpg', 'jpg', 'hanglamp,lampionlamp,bruin'),
	(248, 'Huushinne 25-05-2022-0200.jpg', 'jpg', ''),
	(252, 'Product foto\'s 09-02-2022-274.jpg', 'jpg', ''),
	(255, 'Huushinne 25-05-2022-0230.jpg', 'jpg', ''),
	(258, 'Huushinne 06-04-2022-65530.jpg', 'jpg', 'kussen, kussens, linnen kussen'),
	(259, 'Huushinne 06-04-2022-6599.jpg', 'jpg', 'mand,wasmand,zeegras'),
	(260, 'Huushinne 06-04-2022-6599.jpg', 'jpg', 'mand,wasmand,zeegras'),
	(264, 'Huushinne 06-04-2022-6577.jpg', 'jpg', 'mand,wasmand,speelgoedmand'),
	(265, 'Huushinne 06-04-2022-6579.jpg', 'jpg', 'mand,wasmand,zeegras'),
	(266, 'Huushinne 06-04-2022-6585.jpg', 'jpg', ''),
	(267, 'Huushinne 06-04-2022-6599.jpg', 'jpg', 'mand,wasmand,zeegras'),
	(272, 'Huushinne 30-03-2022-64490.jpg', 'jpg', 'mand bamboe'),
	(275, 'Huushinne 23-03-2022-6383.jpg', 'jpg', 'plaid,malagoon'),
	(276, 'Huushinne 18-05-2022-8893.jpg', 'jpg', 'wand, mand'),
	(278, 'Huushinne-01-06-2022-9164.jpg', 'jpg', ''),
	(279, 'Huushinne-01-06-2022-9165.jpg', 'jpg', 'wand, mand'),
	(280, 'Huushinne 06-04-2022-65490.jpg', 'jpg', 'kandelaar klei'),
	(281, 'Huushinne 06-04-2022-65490.jpg', 'jpg', 'kandelaar klei'),
	(282, 'Huushinne 18-05-2022-88930.jpg', 'jpg', 'wand mand'),
	(283, 'Huushinne 06-04-2022-65490.jpg', 'jpg', 'kandelaar klei'),
	(284, 'Huushinne 06-04-2022-65490.jpg', 'jpg', 'kandelaar klei'),
	(286, 'Productfoto\'s 11-11-2021-1470.jpg', 'jpg', ''),
	(288, 'Huushinne-productfotografie-lantaarn-83470.jpg', 'jpg', ''),
	(290, 'Huushinne-productfotografie-lantaarn-83730.jpg', 'jpg', 'mok, hkliving'),
	(291, 'Huushinne-01-06-2022-9160.jpg', 'jpg', ''),
	(293, 'Huushinne-01-06-2022-9160.jpg', 'jpg', ''),
	(294, 'Huushinne-01-06-2022-91610.jpg', 'jpg', ''),
	(299, 'Huushinne-01-06-2022-91700.jpg', 'jpg', ''),
	(300, 'Huushinne-01-06-2022-9165.jpg', 'jpg', 'waterkan,sapkan,deweldaad'),
	(301, 'Huushinne-01-06-2022-9171.jpg', 'jpg', ''),
	(302, 'Huushinne-01-06-2022-91790.jpg', 'jpg', 'kandelaar klei'),
	(303, 'Huushinne-01-06-2022-9181.jpg', 'jpg', 'kandelaar, zwart'),
	(304, 'Huushinne 30-03-2022-64490.jpg', 'jpg', 'mand zeegras'),
	(305, 'Huushinne-01-06-2022-9152.jpg', 'jpg', 'mand, mandje, opbergmand'),
	(306, 'Huushinne-01-06-2022-9149.jpg', 'jpg', 'mand, mandje, opbergmand'),
	(307, 'Huushinne 11-05-2022-8882.jpg', 'jpg', 'kussen,antraciet,wol,malagoon'),
	(308, '23-02-2022-6193.jpg', 'jpg', ''),
	(309, '23-02-2022-6190.jpg', 'jpg', ''),
	(311, 'Huushinne 30-03-2022-6477.jpg', 'jpg', ''),
	(312, 'Huushinne 13-04-2022-6674-2.jpg', 'jpg', ''),
	(313, 'plaid cheyenne zwart wit3.jpg', 'jpg', 'plaid zwart wit'),
	(314, '04-05-2022-74420.jpg', 'jpg', 'plaid beige blokken hkliving'),
	(315, 'Huushinne 02-03-2022-6317-20.jpg', 'jpg', 'plaid,wit,hkliving'),
	(316, 'Huushinne 02-03-2022-63230.jpg', 'jpg', 'plaid zwart wit hkliving'),
	(317, '04-05-2022-74450.jpg', 'jpg', 'plaid-deken-malagoon-zwart'),
	(320, 'Huushinne 23-03-2022-63880.jpg', 'jpg', 'kussen malagoon'),
	(321, 'Huushinne 23-03-2022-63880.jpg', 'jpg', 'kussen malagoon'),
	(322, '23-02-2022-61821.jpg', 'jpg', ''),
	(323, 'Huushinne 11-05-2022-88600.jpg', 'jpg', ''),
	(324, 'Huushinne 25-05-2022-0091.jpg', 'jpg', 'kussen, kussens, linnen kussen'),
	(325, '23-02-2022-61280.jpg', 'jpg', ''),
	(326, 'Huushinne 11-05-2022-88650.jpg', 'jpg', ''),
	(327, 'Huushinne 11-05-2022-88820.jpg', 'jpg', ''),
	(328, 'Product foto\'s 09-02-2022-2651.jpg', 'jpg', 'egg chair'),
	(329, 'Huushinne-02-02-2022-57412.jpg', 'jpg', 'hocker  householdhardware'),
	(330, 'Productfoto\'s 11-11-2021-1730.jpg', 'jpg', ''),
	(331, 'sfeerfoto\'s-18-11-2021-27830.jpg', 'jpg', ''),
	(332, 'Productfoto\'s 11-11-2021-1470.jpg', 'jpg', ''),
	(333, 'Huushinne-01-06-2022-91540.jpg', 'jpg', ''),
	(334, 'Huushinne-01-06-2022-91790.jpg', 'jpg', 'kandelaar klei'),
	(335, 'Huushinne-01-06-2022-91700.jpg', 'jpg', ''),
	(336, '23-02-2022-6122.jpg', 'jpg', 'de weldaad'),
	(337, 'Huushinne 02-03-2022-63030.jpg', 'jpg', 'plaid beige De Weldaad'),
	(338, 'Huushinne 25-05-2022-0340.jpg', 'jpg', 'kussen, kussens, linnen kussen'),
	(339, 'Productfoto\'s 11-11-2021-1470.jpg', 'jpg', ''),
	(340, 'Huushinne-01-06-2022-91651.jpg', 'jpg', ''),
	(341, 'Huushinne-01-06-2022-91610.jpg', 'jpg', ''),
	(342, 'Huushinne-01-06-2022-91602.jpg', 'jpg', ''),
	(344, 'Huushinne 30-03-2022-64780.jpg', 'jpg', ''),
	(347, 'Huushinne 30-03-2022-64780.jpg', 'jpg', ''),
	(351, '04-05-2022-74200.jpg', 'jpg', ''),
	(353, '23-02-2022-61260.jpg', 'jpg', 'Groot kussen tufted in de kleur beige'),
	(354, '23-02-2022-6100.jpg', 'jpg', 'kussen hkliving'),
	(355, '23-02-2022-61002.jpg', 'jpg', 'kussen hkliving'),
	(356, '23-02-2022-61002.jpg', 'jpg', 'kussen hkliving'),
	(357, '23-02-2022-61002.jpg', 'jpg', 'kussen hkliving'),
	(361, '04-05-2022-73470.jpg', 'jpg', 'tafellamp hkliving'),
	(362, '04-05-2022-73470.jpg', 'jpg', 'tafellamp hkliving'),
	(363, '23-02-2022-61002.jpg', 'jpg', 'kussen hkliving'),
	(365, '04-05-2022-73470.jpg', 'jpg', 'tafellamp hkliving'),
	(366, '04-05-2022-7333.jpg', 'jpg', 'strandmand ,boodschappenmand'),
	(367, 'Huushinne 02-03-2022-6269.jpg', 'jpg', 'sieraden'),
	(368, 'Huushinne 06-04-2022-6565.jpg', 'jpg', 'tassen'),
	(369, '04-05-2022-7333.jpg', 'jpg', ''),
	(371, 'Huushinne 30-03-2022-64270.jpg', 'jpg', 'vaas hkliving'),
	(377, 'Huushinne_15-06-2022-9252.jpg', 'jpg', 'Olijfolie balsamico nicoals vahÃ©'),
	(378, 'Huushinne_15-06-2022-9245.jpg', 'jpg', 'Olijfolie balsamico nicoals vahÃ©'),
	(379, 'Huushinne_15-06-2022-92520.jpg', 'jpg', ''),
	(381, 'Huushinne 30-03-2022-647801.jpg', 'jpg', 'peper,zout,nicolas vahÃ©'),
	(382, 'Huushinne_15-06-2022-92520.jpg', 'jpg', ''),
	(386, 'Huushinne_15-06-2022-92560.jpg', 'jpg', ''),
	(388, 'Huushinne_15-06-2022-9246.jpg', 'jpg', 'balsamico azijn nicolas vahÃ©'),
	(389, 'Huushinne_15-06-2022-9250.jpg', 'jpg', 'balsamico azijn nicolas vahÃ©'),
	(390, 'Huushinne_15-06-2022-92460.jpg', 'jpg', ''),
	(392, 'Huushinne_15-06-2022-9240.jpg', 'jpg', 'olijfolie,kruiden,basiclicum,nicolas vahÃ©'),
	(393, 'Huushinne_15-06-2022-9245.jpg', 'jpg', 'olijfolie,kruiden,basiclicum,nicolas vahÃ©'),
	(394, 'Huushinne_15-06-2022-92400.jpg', 'jpg', ''),
	(395, 'Huushinne_15-06-2022-9207.jpg', 'jpg', 'koffie siroop,nicolas vahÃ©'),
	(396, 'Huushinne_15-06-2022-9209.jpg', 'jpg', 'koffie siroop,nicolas vahÃ©'),
	(398, 'Huushinne_15-06-2022-9207.jpg', 'jpg', ''),
	(399, 'Huushinne_15-06-2022-9209.jpg', 'jpg', ''),
	(400, 'Huushinne_15-06-2022-92071.jpg', 'jpg', ''),
	(402, 'Huushinne_15-06-2022-92092.jpg', 'jpg', 'koffie siroop nicolas vahÃ©'),
	(405, 'Huushinne_15-06-2022-92240.jpg', 'jpg', 'noodle bowls,hkliving'),
	(406, 'Huushinne 23-03-2022-6385.jpg', 'jpg', 'Donker grijs met wit kussen Malagoon'),
	(407, 'Huushinne_15-06-2022-9254.jpg', 'jpg', ''),
	(409, 'Huushinne_15-06-2022-9246.jpg', 'jpg', ''),
	(437, 'Huushinne_22-06-2022-9400.jpg', 'jpg', ''),
	(438, 'Huushinne_22-06-2022-9400.jpg', 'jpg', ''),
	(439, 'Huushinne_22-06-2022-9402.jpg', 'jpg', ''),
	(442, 'Huushinne_22-06-2022-9383.jpg', 'jpg', 'tapas bowls hkliving'),
	(443, 'Huushinne_22-06-2022-9383.jpg', 'jpg', 'tapas bowls hkliving'),
	(444, 'Huushinne_22-06-2022-9383.jpg', 'jpg', 'tapas bowls hkliving'),
	(446, 'Huushinne_22-06-2022-9389.jpg', 'jpg', ''),
	(447, 'Huushinne_22-06-2022-93891.jpg', 'jpg', 'tapas bowls hkliving'),
	(448, 'labbradoriet ring.jpg', 'jpg', 'ring labradoriet'),
	(449, 'labradoriet ring sfeer.jpg', 'jpg', 'ring labradoriet'),
	(450, 'labbradoriet ring0.jpg', 'jpg', 'ring labradoriet a beautiful story'),
	(451, 'labradoriet ring sfeer.jpg', 'jpg', 'ring labradoriet a beautiful story'),
	(452, 'BL26206_600x600.jpg', 'jpg', 'armband black onyx'),
	(453, 'BL26206_1_200x200.jpg black onyx armband.jpg', 'jpg', 'armband black onyx goud'),
	(456, 'glitter black onyx.jpg', 'jpg', 'armband black onyx a beautiful story'),
	(457, 'glitter black onyx.jpg', 'jpg', 'armband black onyx a beautiful story'),
	(459, 'glitter black onyx.jpg', 'jpg', 'armband black onyx a beautiful story'),
	(464, 'Huushinne_22-06-2022-93110.jpg', 'jpg', 'jurk katoen '),
	(465, 'Huushinne 13-04-2022-6660.jpg', 'jpg', ''),
	(466, 'Huushinne 13-04-2022-6671.jpg', 'jpg', 'jurk simple '),
	(467, 'Huushinne 13-04-2022-66710.jpg', 'jpg', 'jurk simple '),
	(473, 'Huushinne-29-06-2022-9505.jpg', 'jpg', ''),
	(474, 'Huushinne-29-06-2022-9509.jpg', 'jpg', ''),
	(476, 'Huushinne-29-06-2022-9511.jpg', 'jpg', ''),
	(477, 'Huushinne-29-06-2022-9493.jpg', 'jpg', ''),
	(479, 'Huushinne-29-06-2022-9504.jpg', 'jpg', ''),
	(480, 'Huushinne-29-06-2022-9502.jpg', 'jpg', ''),
	(481, 'Huushinne-29-06-2022-9499.jpg', 'jpg', ''),
	(482, 'Huushinne-29-06-2022-9499.jpg', 'jpg', ''),
	(483, 'Huushinne-29-06-2022-9499.jpg', 'jpg', ''),
	(484, 'Huushinne-29-06-2022-9501.jpg', 'jpg', ''),
	(486, 'Huushinne 30-03-2022-6471.jpg', 'jpg', 'ovenschaal,casafina'),
	(487, 'Huushinne-29-06-2022-9486.jpg', 'jpg', 'ovenschaal,casafina'),
	(491, 'Huushinne-29-06-2022-94880.jpg', 'jpg', ''),
	(492, 'Huushinne-29-06-2022-9483.jpg', 'jpg', ''),
	(494, 'Huushinne-29-06-2022-9470.jpg', 'jpg', 'hkliving, jungle, bord'),
	(495, 'Huushinne-29-06-2022-9473.jpg', 'jpg', 'hkliving, jungle, bord'),
	(496, 'Huushinne-29-06-2022-94700.jpg', 'jpg', 'hkliving, jungle, bord'),
	(497, 'Huushinne-29-06-2022-9471.jpg', 'jpg', 'hkliving, jungle, bord'),
	(500, 'Huushinne-29-06-2022-9473.jpg', 'jpg', 'hkliving, jungle, kom'),
	(508, 'Huushinne-29-06-2022-9417.jpg', 'jpg', ''),
	(510, 'Huushinne-29-06-2022-9423.jpg', 'jpg', 'hkliving, gradient, servies, mok'),
	(513, 'Huushinne-29-06-2022-9423.jpg', 'jpg', 'hkliving, gradient, servies, bord, ontbijt'),
	(517, 'Huushinne-29-06-2022-9423.jpg', 'jpg', 'hkliving, gradient, servies, bord, diner'),
	(519, 'Huushinne-29-06-2022-9431.jpg', 'jpg', ''),
	(524, 'Huushinne-29-06-2022-9435.jpg', 'jpg', 'hkliving, gradient, servies, mok'),
	(527, 'Huushinne-29-06-2022-9435.jpg', 'jpg', 'hkliving, gradient, servies, bord, ontbijt'),
	(528, 'Huushinne-29-06-2022-94700.jpg', 'jpg', 'jungle dinerbord'),
	(532, 'Huushinne-29-06-2022-9435.jpg', 'jpg', 'hkliving, dinerbord, groen, huushinne'),
	(533, 'Huushinne-29-06-2022-947001.jpg', 'jpg', 'ontbijtbord jungle hkliving'),
	(534, 'Huushinne-29-06-2022-94630.jpg', 'jpg', 'kom jungle servies hkliving'),
	(535, 'Huushinne-29-06-2022-9471.jpg', 'jpg', 'servies jungle hkliving'),
	(536, 'Huushinne-29-06-2022-9473.jpg', 'jpg', 'servies jungle hkliving'),
	(537, 'Huushinne_15-06-2022-9224.jpg', 'jpg', 'noodle bowls hkliving'),
	(538, 'Huushinne_22-06-2022-93950.jpg', 'jpg', 'dessert kommen hkliving'),
	(540, 'Huushinne_15-06-2022-9279.jpg', 'jpg', 'kookboek,jamie oliver,tx anders'),
	(566, 'Huushinne-29-06-2022-9413.jpg', 'jpg', 'bord, ontbijtbord, gradient, hkliving, roze'),
	(571, 'Huushinne-29-06-2022-9405.jpg', 'jpg', 'mok, gradient, hkliving, roze'),
	(572, 'Huushinne-29-06-2022-9405.jpg', 'jpg', 'mok, gradient, hkliving, roze'),
	(574, 'Huushinne-29-06-2022-9413.jpg', 'jpg', 'mok, gradient, hkliving, roze'),
	(576, 'Huushinne_22-06-2022-93710.jpg', 'jpg', 'mijnb stijl,handzeep,douchegel'),
	(577, 'Huushinne_22-06-2022-93740.jpg', 'jpg', 'mijn stijl,handzeep,douchegel,vijg'),
	(578, 'Huushinne-29-06-2022-94480.jpg', 'jpg', ''),
	(579, 'Huushinne-29-06-2022-94510.jpg', 'jpg', 'mok, zand'),
	(580, 'Huushinne-29-06-2022-94590.jpg', 'jpg', ''),
	(581, 'Huushinne-29-06-2022-94370.jpg', 'jpg', 'mok, zand, zwart'),
	(585, 'Huushinne 18-05-2022-89110.jpg', 'jpg', 'kussen,linnen,wit'),
	(587, '20-07-2022-9588.jpg', 'jpg', 'sapkan,waterkan,de weldaad'),
	(588, '20-07-2022-95880.jpg', 'jpg', 'sapkan,waterkan,de weldaad'),
	(589, 'Huushinne-01-06-2022-9170.jpg', 'jpg', 'sapkan,waterkan,deweldaad'),
	(591, 'Huushinne 11-05-2022-88700.jpg', 'jpg', 'kussen hkliving'),
	(592, '23-02-2022-6205.jpg', 'jpg', 'kussen,hkliving'),
	(593, 'Huushinne 11-05-2022-88860.jpg', 'jpg', 'kussen, hkliving,olijfkleur'),
	(594, 'Huushinne 11-05-2022-88730.jpg', 'jpg', 'kussen householdhardware'),
	(595, '23-02-2022-61171.jpg', 'jpg', 'kussen,olijfgroen,hkliving,velours'),
	(596, '23-02-2022-6120.jpg', 'jpg', 'kussen,olijfgroen,velours,hkliving'),
	(598, 'Huushinne-29-06-2022-9478.jpg', 'jpg', 'pan '),
	(599, 'Huushinne-29-06-2022-9479.jpg', 'jpg', 'koekenpan ,BAF'),
	(600, 'Huushinne-29-06-2022-9478.jpg', 'jpg', 'koekenpan,BAF'),
	(601, '23-02-2022-61841.jpg', 'jpg', ''),
	(602, 'Huushinne 27-07-2022-9944.jpg', 'jpg', 'jurk bruin/beige'),
	(605, 'Huushinne 06-04-2022-6624.jpg', 'jpg', ''),
	(606, 'Huushinne 06-04-2022-6624.jpg', 'jpg', 'confiture lamp '),
	(607, 'Huushinne 06-04-2022-6604.jpg', 'jpg', ''),
	(612, 'P6058 Pembroke - Beige.jpg', 'jpg', 'jurk JcSophie'),
	(613, 'P6058 Pembroke - Beige.jpg', 'jpg', ''),
	(614, '2022_01_26_F22JCSophie_19_4283.jpg', 'jpg', ''),
	(616, 'P6058 Pembroke - Beige.jpg', 'jpg', ''),
	(629, 'BL25137_3.jpg', 'jpg', 'ring, citrine, a beautiful story'),
	(630, 'BL25037_3.jpg', 'jpg', ''),
	(631, 'BL25037_30.jpg', 'jpg', 'ring, garnet, granaat, a beautiful story'),
	(636, 'bl23376-sparkle-tiger-eye-gold-card_600x600.jpg', 'jpg', 'ring, tijgeroog, a beautiful story'),
	(640, 'bl22576-sparkle-blue-lace-agate-silver-card.jpg', 'jpg', 'ring, blue lace agate, blauwe agaat, a beautiful story'),
	(642, 'Mondstein_bl22376.jpg', 'jpg', 'ring, edelsteen, a beautiful story, maansteen, moonstone'),
	(648, 'bl23576-sparkle-lapis-lazuli-silver-card.jpg', 'jpg', 'ring, lapis lazuli, a beautiful story'),
	(650, 'BL25337.jpg', 'jpg', 'ring, aventurine, aventurijn, a beautiful story'),
	(651, 'BL25337_3.jpg', 'jpg', 'ring, aventurine, aventurijn, a beautiful story'),
	(652, 'bl22876-sparkle-black-onyx-silver-card0.jpg', 'jpg', 'ring, black onyx, zwarte onyx, a beautiful story'),
	(653, 'bl23476-sparkle-carnelian-gold-card_600x600.jpg', 'jpg', 'ring, carnelian, carneool, a beautiful story'),
	(655, 'bl22476-sparkle-black-onyx-gold-card.jpg', 'jpg', 'ring, black onyx, zwarte onyx, a beautiful story'),
	(659, 'bl22276-sparkle-rose-quartz-silver-card.jpg', 'jpg', 'ring, rozenkwarts, rose quartz, a beautiful story'),
	(660, 'bl23076-sparkle-citrine-gold-card.jpg', 'jpg', 'ring, citrine, a beautiful story'),
	(661, 'BL25137_3.jpg', 'jpg', 'ring, citrine, a beautiful story'),
	(662, 'bl22976-sparkle-garnet-gold-card.jpg', 'jpg', 'ring, garnet, granaat, a beautiful story'),
	(663, 'BL25037_3.jpg', 'jpg', 'ring, garnet, granaat, a beautiful story'),
	(671, 'P6005 Parnika - Beige.jpg', 'jpg', 'blouse Parnika JcSophie'),
	(676, 'BL23374.jpg', 'jpg', 'armband, a beautiful story, tijgeroog'),
	(677, 'BL23374_2.jpg', 'jpg', 'armband, a beautiful story, tijgeroog'),
	(679, 'BL23074.jpg', 'jpg', 'armband, a beautiful story, citrien, citrine'),
	(680, 'BL23074_2.jpg', 'jpg', 'armband, a beautiful story, citrien, citrine'),
	(682, 'BL23474.jpg', 'jpg', 'armband, a beautiful story, carneool, carnelian'),
	(683, 'BL23474_2.jpg', 'jpg', 'armband, a beautiful story, carneool, carnelian'),
	(685, 'BL22974.jpg', 'jpg', 'armband, a beautiful story, garnet, granaat'),
	(686, 'BL22974_2.jpg', 'jpg', 'armband, a beautiful story, garnet, granaat'),
	(688, 'BL22674.jpg', 'jpg', 'armband, a beautiful story, labradorite, labradoriet'),
	(689, 'BL22674_2.jpg', 'jpg', 'armband, a beautiful story, labradorite, labradoriet'),
	(691, 'BL22274.jpg', 'jpg', 'armband, a beautiful story, rozenkwarts, rose quartz'),
	(692, 'BL22274_2.jpg', 'jpg', 'armband, a beautiful story, rozenkwarts, rose quartz'),
	(694, 'BL23174.jpg', 'jpg', 'armband, a beautiful story, smokey quartz, rookkwarts'),
	(695, 'BL23174_2.jpg', 'jpg', 'armband, a beautiful story, smokey quartz, rookkwarts'),
	(697, 'BL23574.jpg', 'jpg', 'armband, a beautiful story, lapis lazuli'),
	(698, 'BL23574_2.jpg', 'jpg', 'armband, a beautiful story, lapis lazuli'),
	(700, 'BL22574.jpg', 'jpg', 'armband, a beautiful story, Blauwe agaat'),
	(701, 'BL22574_2.jpg', 'jpg', 'armband, a beautiful story, Blauwe agaat'),
	(702, 'BL23176-Sparkle-Smokey-Quartz-Ring-S-M-1_200x200@2x.jpg', 'jpg', 'ring, smokey quartz, rookkwarts, a beautiful story'),
	(703, 'BL23176-Sparkle-Smokey-Quartz-Ring-S-M-1_200x200@2x.jpg', 'jpg', 'ring,smokey quarts,abeautiful story'),
	(704, 'bl23176-sparkle-smokey-quartz-silver-card_600x600@2x.jpg', 'jpg', ''),
	(705, 'Huushinne 27-07-2022-039.jpg', 'jpg', ''),
	(706, 'Huushinne winkelfoto\'s-0033.jpg', 'jpg', ''),
	(707, 'Huushinne winkelfoto\'s-0033.jpg', 'jpg', ''),
	(708, 'Huushinne winkelfoto\'s-0033.png', 'png', ''),
	(709, 'Huushinne winkelfoto\'s-0033_600px.jpg', 'jpg', ''),
	(710, 'shopping-basket.png', 'png', ''),
	(711, 'shopping-basket.png', 'png', ''),
	(712, 'Huushinne winkelfoto\'s-0033.jpg', 'jpg', ''),
	(713, 'Huushinne 27-07-2022-039.jpg', 'jpg', ''),
	(714, 'Huushinne winkelfoto\'s-0040.jpg', 'jpg', ''),
	(715, 'lmp47_essaouira-beach-umbrella-600x600.jpg', 'jpg', ''),
	(718, 'newborn setje0.jpg', 'jpg', ''),
	(719, 'newborn setje0.jpg', 'jpg', ''),
	(720, 'newborn setje0.jpg', 'jpg', ''),
	(724, 'Huushinne-24-08-2022-0418.jpg', 'jpg', 'baby, babykleding, kinderkleding, ezzies'),
	(728, 'Huushinne-24-08-2022-041800.jpg', 'jpg', 'baby, babykleding, kinderkleding, ezzies'),
	(730, 'Huushinne-24-08-2022-04140.jpg', 'jpg', 'baby, babykleding, kinderkleding, ezzies'),
	(732, 'Huushinne-24-08-2022-0415.jpg', 'jpg', 'baby, babykleding, kinderkleding, ezzies'),
	(738, 'Huushinne-24-08-2022-0423.jpg', 'jpg', 'baby, kind, peuter, knuffel, konijn'),
	(739, 'Huushinne-24-08-2022-0423.jpg', 'jpg', 'baby, kind, peuter, knuffel, konijn'),
	(740, 'Huushinne-24-08-2022-0424.jpg', 'jpg', 'baby, kind, peuter, knuffel, konijn'),
	(742, 'Huushinne-24-08-2022-0421.jpg', 'jpg', 'baby, kind, peuter, knuffel, aap'),
	(743, 'Huushinne-24-08-2022-0422.jpg', 'jpg', 'baby, kind, peuter, knuffel, aap'),
	(747, 'Huushinne-24-08-2022-0425.jpg', 'jpg', 'baby, kind, peuter, knuffel, aap'),
	(748, 'Huushinne-24-08-2022-0426.jpg', 'jpg', 'baby, kind, peuter, knuffel, aap'),
	(749, 'Woonspullen 16-02-2022-5994.jpg', 'jpg', ''),
	(750, 'Woonspullen 16-02-2022-59940.jpg', 'jpg', ''),
	(751, 'Woonspullen 16-02-2022-599400.jpg', 'jpg', ''),
	(752, 'Woonspullen 16-02-2022-599400.jpg', 'jpg', 'kadobon,huushinne'),
	(753, 'Woonspullen 16-02-2022-599400.jpg', 'jpg', ''),
	(798, 'Huushinne winkelfoto\'s-0033.jpg', 'jpg', ''),
	(799, 'Huushinne 27-07-2022-039.jpg', 'jpg', ''),
	(814, 'Carolyn-magnet-evy-purezza_600x600@2x.jpg', 'jpg', 'jas carolyn simple gr4ijs'),
	(815, 'Carolun-magnet_600x600@2x.jpg', 'jpg', 'jas carolyn simple grijs'),
	(822, 'Degrade-Magnet-fallin-white-1_600x600@2x.jpg', 'jpg', 'vest, simple'),
	(842, 'FW22-1_Simple75_600x600.jpg', 'jpg', 'simple, jas'),
	(859, '2022-11-02 Huushinne-1142.jpg', 'jpg', 'kandelaar hoog hout'),
	(861, 'Huushinne 2022-10-19-0944.jpg', 'jpg', 'kerstster,offwhite,'),
	(864, '2022-11-02 Huushinne-1122.jpg', 'jpg', 'bijzettafel hkliving '),
	(865, 'Huushinne 2022-10-26-1064.jpg', 'jpg', 'mistletoe,messing'),
	(870, 'Huushinne 2022-12-07-1586.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(871, 'Huushinne 2022-12-07-1583.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(873, 'Huushinne 2022-12-07-1582.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(874, 'Huushinne 2022-12-07-15860.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(875, 'Huushinne 2022-12-07-15860.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(876, 'Huushinne 2022-12-07-15860.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(881, 'Huushinne 2022-12-07-15860.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(882, 'Huushinne 2022-12-07-15860.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(883, 'Huushinne 2022-12-07-15860.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(884, 'Huushinne 2022-12-07-1589.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(885, 'Huushinne 2022-12-07-1587.jpg', 'jpg', 'oorbellen,graceful,edelsteen,abeautifulstory'),
	(886, 'Huushinne 2022-12-07-1582.jpg', 'jpg', ''),
	(889, 'Huushinne 2022-12-21-17470.jpg', 'jpg', 'sweater dress'),
	(895, 'Huushinne 2023-01-11-1874-2.jpg', 'jpg', 'lamp,raffia'),
	(898, 'Huushinne 2023-01-11-1916-2.jpg', 'jpg', ''),
	(900, 'Huushinne 2023-01-11-1919-2.jpg', 'jpg', 'oorbel, lapis lazuli, beautiful story'),
	(901, 'Huushinne 2023-01-11-1918-2.jpg', 'jpg', 'oorbel, lapis lazuli, beautiful story'),
	(903, 'Huushinne 2023-01-11-1920-2.jpg', 'jpg', 'oorbellen, onyx, a beautiful story'),
	(904, 'Huushinne 2023-01-11-1921-2.jpg', 'jpg', 'oorbellen, onyx, a beautiful story'),
	(906, 'Huushinne 2023-01-11-1940-2.jpg', 'jpg', 'tijgeroog, oorbellen, a beautiful story'),
	(910, 'Huushinne 2023-01-11-1926-2.jpg', 'jpg', 'oorbellen, a beautiful story, rozenkwarts'),
	(911, 'Huushinne 2023-01-11-1928-2.jpg', 'jpg', 'oorbellen, a beautiful story, rozenkwarts'),
	(913, 'Huushinne 2023-01-11-1937-2.jpg', 'jpg', 'oorbel, blauwe agaat, beautiful story'),
	(915, 'Huushinne 2023-01-04-1863-2.jpg', 'jpg', 'opbergmand, wasmand, speelgoedmand'),
	(916, 'Huushinne 2023-01-04-1865.jpg', 'jpg', 'opbergmand, wasmand, speelgoedmand'),
	(921, 'kussen thine striped5.jpg', 'jpg', 'kussen thin striped hkliving'),
	(926, 'Huushinne 2023-01-04-1869-2.jpg', 'jpg', 'kussen blockprint'),
	(928, '2023-03-09 Huushinne-2586.jpg', 'jpg', 'hkliving, bowl, currybowl'),
	(929, '2023-03-09 Huushinne-2599.jpg', 'jpg', 'hkliving, bowl, currybowl'),
	(937, '2023-03-09 Huushinne-2581.jpg', 'jpg', 'hkliving, bowl, currybowl'),
	(939, '2023-03-09 Huushinne-2598.jpg', 'jpg', 'hkliving, bowl, currybowl'),
	(982, '2023-03-15 Huushinne-2647.jpg', 'jpg', 'jcsophie, blouse'),
	(990, '2023-04-05 Huushinne-2992-2.jpg', 'jpg', ''),
	(992, '2023-04-05 Huushinne-2991-2.jpg', 'jpg', ''),
	(995, '2023-06-14 Huushinne-3643.jpg', 'jpg', 'lamp, katoen, hanglamp, plafondlamp'),
	(996, '2023-06-14 Huushinne-3644.jpg', 'jpg', 'lamp, katoen, hanglamp, plafondlamp'),
	(1000, '2023-04-26 Huushinne-3242.jpg', 'jpg', 'kussen householdhardware roze '),
	(1001, 'ace7174_eg.jpg', 'jpg', 'HKliving, Noodle bowl, Groovy'),
	(1002, 'hap6123_eg.jpg', 'jpg', ''),
	(1005, '2023-04-26 Huushinne-3242-2.jpg', 'jpg', 'kussen householdhardware roze '),
	(1010, '2023_01_27V1_JCSophieFall_LB23_1_072.jpg', 'jpg', 'trui jcsophie'),
	(1015, 'A1580 - AIR - 372 - DARK BLUE STRIPES - FRONT.jpg', 'jpg', 't shirt air jcsophie'),
	(1017, 'front A1580 - AIR - 372 - DARK BLUE STRIPES - FRONT.jpg', 'jpg', 't shirt air jcsophie'),
	(1020, '2023-08-16 Huushinne-5200.jpg', 'jpg', 'kussen householdhardware'),
	(1022, 'badmat monochrome.jpg', 'jpg', 'badmat monochrome hkliving huushinne'),
	(1023, 'badmat monochrome hkliving.jpg', 'jpg', 'badmat monochrome hkliving '),
	(1024, 'kussen zwart witte blokken hkliving.jpg', 'jpg', ''),
	(1027, '10508241_1513051_400.jpg', 'jpg', 'vest Rachel kaffe '),
	(1028, '10508241_1513051_400.jpg', 'jpg', ''),
	(1035, 'antique-white-midnight-stripe-kawinny-t-shirt.jpg', 'jpg', 'shirt Winny kaffe'),
	(1036, 'kawinny.jpg', 'jpg', 'shirt Winny kaffe'),
	(1038, 'faded-denim-kaelena-pullover.jpg', 'jpg', 'trui elena kaffe'),
	(1039, 'faded-denim-kaelena-pullover.jpg', 'jpg', 'trui elena kaffe'),
	(1042, 'plaid linnen zand.jpg', 'jpg', 'plaid linnen zand'),
	(1043, 'plaid linne zand hk.jpg', 'jpg', ''),
	(1044, '2023-08-16 Huushinne-6880-2.jpg', 'jpg', ''),
	(1045, '2023-08-16 Huushinne-6880-2.jpg', 'jpg', ''),
	(1046, '10508204_194020_600.jpg', 'jpg', 'bomber jack Kaffe'),
	(1047, '10508204_194020_600.jpg', 'jpg', ''),
	(1058, 'ttk3111-eg_01.jpg', 'jpg', 'vloerkleed hklving emmen'),
	(1059, '2023-08-16 Huushinne-8966.jpg', 'jpg', 'vloerkleed hkliving huushinne emmen'),
	(1060, 'vloerkleed house doctor zwart wit.jpg', 'jpg', 'vloerkleed House Doctor huushinne emmen'),
	(1065, 'jurk kalola grijs.jpg', 'jpg', 'jurk kalola kaffe'),
	(1066, 'jurk kalola kaffe.jpg', 'jpg', 'jurk KALOLA KAFFE EMMEN'),
	(1070, 'kalinea sweater groen.jpg', 'jpg', ''),
	(1073, 'kalinea sweater groen s.jpg', 'jpg', ''),
	(1074, 'ttk3095-lr_02.jpg', 'jpg', 'vloerkleed HKLiivng'),
	(1075, 'ttk3095-lr_vrij_a_01.png', 'png', ''),
	(1076, '2023-08-16 Huushinne-8927-2.jpg', 'jpg', 'tajine mand huushinne'),
	(1077, '2023-08-16 Huushinne-8942-2.jpg', 'jpg', 'tajine mand bruin '),
	(1078, '2023-08-16 Huushinne-8942-2.jpg', 'jpg', 'tajine mand huushinne'),
	(1080, '2024-03-20 Huushinne-7548.jpg', 'jpg', 'tajine mand marokko'),
	(1081, '2024-03-20 Huushinne-7561-2.jpg', 'jpg', 'hanglamp Marokko '),
	(1082, '2024-03-20 Huushinne-7564-2.jpg', 'jpg', 'hanglamp marokko'),
	(1084, '2024-03-20 Huushinne-7570-2.jpg', 'jpg', 'tajine palmblad '),
	(1085, '2023-08-16 Huushinne-7721.jpg', 'jpg', 'kussen householdhardware'),
	(1086, '2023-08-16 Huushinne-9096 - kopie.jpg', 'jpg', 'kussen,zwart wit '),
	(1087, '2023-08-16 Huushinne-9099 - kopie.jpg', 'jpg', 'kussen,grijs,huushinne'),
	(1088, '2023-08-16 Huushinne-9093.jpg', 'jpg', 'kussen gradient hklving'),
	(1089, '2023-08-16 Huushinne-9075.jpg', 'jpg', 'kussen gradient hklving');

-- Dumping structure for table db3749273_thuisbijdekat.pages
CREATE TABLE IF NOT EXISTS `pages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(250) NOT NULL,
  `description` varchar(20000) DEFAULT NULL,
  `sort_order` int(10) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table db3749273_thuisbijdekat.pages: ~11 rows (approximately)
INSERT INTO `pages` (`id`, `name`, `description`, `sort_order`) VALUES
	(2, 'Betalen', '<p><br></p><p>Al onze betalingen gaan via <a href="https://www.mollie.com/nl/consumers" target="_blank">Mollie</a>, een zogenoemde betaalprovider.</p><p>Mollie is een tussenpersoon die de betalingen regelt via een beveiligde verbinding.</p><p><br></p><p>----------------------------------------------</p><h5><strong>Nederland</strong></h5><p><br></p><p>In Nederland kunt u betalen via:</p><p><br></p><p><img src="https://www.mollie.com/external/icons/payment-methods/ideal%402x.png"> iDeal</p><p><br></p><p><img src="https://www.mollie.com/external/icons/payment-methods/creditcard%402x.png"> Credit Card</p><p><br></p><p><img src="https://www.mollie.com/external/icons/payment-methods/paypal%402x.png"></img> Paypal</p><p><br></p><p>----------------------------------------------</p><h5><strong>BelgiÃ«</strong></h5><p><br></p><p>In BelgiÃ« kunt u betalen via:</p><p><br></p><p><img src="https://www.mollie.com/external/icons/payment-methods/creditcard%402x.png"> Credit Card</p><p><br></p><p><img src="https://www.mollie.com/external/icons/payment-methods/paypal%402x.png"></img> Paypal</p><p><br></p><p><img src="https://www.mollie.com/external/icons/payment-methods/bancontact%402x.png"> Bancontact</p><p><br></p><p><img src="https://www.mollie.com/external/icons/payment-methods/kbc%402x.png"> KBC/CBC Payment Button</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>', 4),
	(5, 'Privacy Verklaring', '<p><br></p><h5><strong><u>Bedrijfsgegevens</u></strong></h5><p><br></p><p>HUUSHINNE</p><p>Dalipassage 2</p><p>7811DB EMMEN</p><p><br></p><p>Handelsnaam: MSSTYLING</p><p>K.V.K. nummer: 61545988</p><p>BTW-nummer: NL 854384777B01</p><p>IBAN: NL98 KNAB 0256 9986 71</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong><u>Over ons privacybeleid</u></strong></h5><p><br></p><p>MSSTYLING/HUUSHINNE geeft veel om uw privacy. Wij verwerken daarom uitsluitend gegevens die wij nodig hebben voor (het verbeteren van) onze dienstverlening en gaan zorgvuldig om met de informatie die wij over u en uw gebruik van onze diensten hebben verzameld. Wij stellen uw gegevens nooit voor commerciele doelstellingen ter beschikking aan derden.</p><p><br></p><p>Dit privacybeleid is van toepassing op het gebruik van de website en de daarop ontsloten dienstverlening van MSSTYLING/HUUSHINNE. De ingangsdatum voor de geldigheid van deze voorwaarden is 17/12/2019, met het publiceren van een nieuwe versie vervalt de geldigheid van alle voorgaande versies. Dit privacybeleid beschrijft welke gegevens over u door ons worden verzameld, waar deze gegevens voor worden gebruikt en met wie en onder welke voorwaarden deze gegevens eventueel met derden kunnen worden gedeeld. Ook leggen wij aan u uit op welke wijze wij uw gegevens opslaan en hoe wij uw gegevens tegen misbruik beschermen en welke rechten u heeft met betrekking tot de door u aan ons verstrekte persoonsgegevens. Als u vragen heeft over ons privacybeleid kunt u contact opnemen met onze contactpersoon voor privacyzaken, u vindt de contactgegevens aan het einde van ons privacybeleid.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong><u>Over de gegevensverwerking</u></strong></h5><p><br></p><p>Hieronder kan u lezen op welke wijze wij uw gegevens verwerken, waar wij deze (laten) opslaan, welke beveiligingstechnieken wij gebruiken en voor wie de gegevens inzichtelijk zijn.</p><p><br></p><h5><strong>Webwinkelsoftware</strong></h5><p><br></p><p>Onze webwinkel is ontwikkeld door een interne developer en maakt geen gebruik van andere externe frameworks of programma\'s die toegang hebben tot uw klantgegevens. Al uw persoonsgegevens worden veilig opgeslagen in onze database en is niet toegankelijk voor externe bronnen. Onze software bevat verschillende beveiligingstechnieken waarmee wij ervoor zorgen dat uw persoonsgegevens veilig opgeslagen zijn.</p><p><br></p><h5><strong>Webhosting</strong></h5><p><br></p><p>Wij nemen webhosting- en e-maildiensten af van Transip. Transip verwerkt gegevens namens ons en gebruikt uw gegevens niet voor eigen doeleinden. Wel kan deze partij metagegevens verzamelen over het gebruik van de diensten. Dit zijn geen persoonsgegevens. Transip heeft passende technische en organisatorische maatregelen genomen om verlies en ongeoorloofd gebruik van uw persoonsgegevens te voorkomen. Transip is op grond van de overeenkomst tot geheimhouding verplicht.</p><p><br></p><h5><strong>Beveiligde verbinding (SSL)</strong></h5><p><br></p><p>Tijdens het aanmaken van een account en het plaatsen van een bestelling worden uw gegevens versleuteld en via een beveiligde verbinding (SSL) naar ons verzonden. Uw gegevens kunnen tijdens de overdracht over het internet niet worden gelezen door andere personen. Hiermee bieden wij u veiligheid tijdens de overdacht van uw gegevens tegen diefstal en misbruik via het internet. Deze beveiligde verbinding is te herkennen aan het groene slotje in de adresbalk links bovenaan uw scherm en aan de url: hier hoort https://www.huushinne.nl te staan.</p><p><br></p><h5><strong>Cookies</strong></h5><p><br></p><p>Cookies zijn kleine stukjes informatie die door uw browser worden opgeslagen op uw computer. Huushinne.nl gebruikt cookies om u te herkennen bij een volgend bezoek. Onze cookies geven informatie met betrekking tot persoonsidentificatie. Onze cookies bevatten geen persoonsgegevens en zullen u ook niet volgen (Geen tracking cookies).</p><p><br></p><h5><strong>E-mail en mailinglijsten</strong></h5><p><br></p><p>Wij versturen onze e-mail nieuwsbrieven met MailChimp. MailChimp zal uw naam en e-mailadres nooit voor eigen doeleinden gebruiken. Onderaan elke e-mail die geautomatiseerd via onze website is verzonden ziet u de unsubscribe link. U ontvangt onze nieuwsbrief dan niet meer. Uw persoonsgegevens worden door MailChimp beveiligd opgeslagen. MailChimp maakt gebruik van cookies en andere internettechnologieÃ«n die inzichtelijk maken of e-mails worden geopend en gelezen. MailChimp behoudt zich het recht voor om uw gegevens te gebruiken voor het verder verbeteren van de dienstverlening en in het kader daarvan informatie met derden te delen.</p><p><br></p><p>Wij maken voor ons reguliere zakelijke e-mailverkeer gebruik van de imap diensten van Transip. Deze partij heeft passende technische en organisatorische maatregelen getroffen om misbruik, verlies en corruptie van uw en onze gegevens zoveel mogelijk te voorkomen. Transip heeft geen toegang tot ons postvak en wij behandelen al ons emailverkeer vertrouwelijk. Het postvak wordt intern opgeslagen en is niet extern bereikbaar.</p><p><br></p><h5><strong>Payment processors/Betaalprovider</strong></h5><p><br></p><p>Voor het afhandelen van een (deel van) de betalingen in onze webwinkel maken wij gebruik van het platform van <a href="https://www.mollie.com/nl/consumers" target="_blank">Mollie</a>. Mollie verwerkt uw naam, adres en woonplaatsgegevens en uw betaalgegevens zoals uw bankrekening- of creditcardnummer. Mollie heeft passende technische en organisatorische maatregelen genomen om uw persoonsgegevens te beschermen. Mollie behoudt zich het recht voor uw gegevens te gebruiken om de dienstverlening verder te verbeteren en in het kader daarvan (geanonimiseerde) gegevens met derden te delen. Alle hierboven genoemde waarborgen met betrekking tot de bescherming van uw persoonsgegevens zijn eveneens van toepassing op de onderdelen van Mollies dienstverlening waarvoor zij derden inschakelen. Mollie bewaart uw gegevens niet langer dan op grond van de wettelijke termijnen is toegestaan.</p><p><br></p><h5><strong>Facturatie en boekhouden</strong></h5><p><br></p><p>Voor het bijhouden van onze administratie en boekhouding maken wij gebruik van de diensten van Twinfield. Wij delen uw naam, adres en woonplaatsgegevens en details met betrekking tot uw bestelling. Deze gegevens worden gebruikt voor het administreren van verkoopfacturen. Voor onze bijhouden van onze administratie en boekhouding maken wij gebruik van de diensten van Twinfield. Wij delen uw naam, adres en woonplaatsgegevens en details met betrekking tot uw bestelling. Deze gegevens worden gebruikt voor het administreren van verkoopfacturen. Uw persoonsgegevens worden beschermd verzonden en opgeslagen. Twinfield is tot geheimhouding verplicht en zal uw gegevens vertrouwelijk behandelen. Twinfield gebruikt uw persoonsgegevens niet voor andere doeleinden dan hierboven beschreven.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong><u>Doel van de gegevensverwerking</u></strong></h5><p><br></p><h5><strong>Algemeen doel van de verwerking</strong></h5><p><br></p><p>Wij gebruiken uw gegevens uitsluitend ten behoeve van onze dienstverlening. Dat wil zeggen dat het doel van de verwerking altijd direct verband houdt met de opdracht die u verstrekt. Wij gebruiken uw gegevens niet voor (gerichte) marketing. Als u gegevens met ons deelt en wij gebruiken deze gegevens om - anders dan op uw verzoek - op een later moment contact met u op te nemen, vragen wij u hiervoor expliciet toestemming. Uw gegevens worden niet met derden gedeeld, anders dan om aan boekhoudkundige en overige administratieve verplichtingen te voldoen. Deze derden zijn allemaal tot geheimhouding gehouden op grond van de overeenkomst tussen hen en ons of een of wettelijke verplichting.</p><p><br></p><h5><strong>Medewerking aan fiscaal en strafrechtelijk onderzoek</strong></h5><p><br></p><p>In voorkomende gevallen kan MSSTYLING/HUUSHINNE op grond van een wettelijke verplichting worden gehouden tot het delen van uw gegevens in verband met fiscaal of strafrechtelijk onderzoek van overheidswege. In een dergelijk geval zijn wij gedwongen uw gegevens te delen.</p><p><br></p><h5><strong>Bewaartermijnen</strong></h5><p><br></p><p>Wij bewaren uw gegevens zolang u klant van ons bent. Dit betekent dat wij uw klantprofiel bewaren totdat u aangeeft dat u niet langer van onze diensten gebruik wenst te maken. Als u dit bij ons aangeeft zullen wij dit tevens opvatten als een vergeetverzoek. Op grond van toepasselijke administratieve verplichtingen dienen wij facturen met uw (persoons) gegevens te bewaren, deze gegevens zullen wij dus voor zolang de toepasselijke termijn loopt bewaren.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong><u>Uw rechten</u></strong></h5><p><br></p><p>Op grond van de geldende Nederlandse en Europese wetgeving heeft u als betrokkene bepaalde rechten met betrekking tot de persoonsgegevens die door of namens ons worden verwerkt. Wij leggen u hieronder uit welke rechten dit zijn en hoe u zich op deze rechten kunt beroepen. In beginsel sturen wij om misbruik te voorkomen afschriften en kopieÃ«n van uw gegevens enkel naar uw bij ons reeds bekende e-mailadres. In het geval dat u de gegevens op een ander e-mailadres wenst te ontvangen, kunt u dit zelf wijzigen in uw account pagina. We zullen wij u dan wel vragen om uw nieuw e-mailadres opnieuw te verifiÃ«ren. Wij houden een administratie bij van afgehandelde verzoeken, in het geval van een vergeetverzoek administreren wij geanonimiseerde gegevens. Alle afschriften en kopieÃ«n van gegevens ontvangt u via de mail. U heeft te allen tijden het recht om een klacht in te dienen bij de Autoriteit Persoonsgegevens als u vermoedt dat wij uw persoonsgegevens op een verkeerde manier gebruiken.</p><p><br></p><h5><strong>Inzagerecht</strong></h5><p><br></p><p>U heeft altijd het recht om de gegevens die wij (laten) verwerken en die betrekking hebben op uw persoon of daartoe herleidbaar zijn, in te zien. U kunt een verzoek met die strekking doen aan onze contactpersoon voor privacyzaken. U ontvangt dan binnen 30 dagen een reactie op uw verzoek. Als uw verzoek wordt ingewilligd sturen wij u op het bij ons bekende e-mailadres een kopie van alle gegevens met een overzicht van de verwerkers die deze gegevens onder zich hebben, onder vermelding van de categorie waaronder wij deze gegevens hebben opgeslagen.</p><p><br></p><h5><strong>Rectificatierecht</strong></h5><p><br></p><p>U heeft altijd het recht om de gegevens die wij (laten) verwerken en die betrekking hebben op uw persoon of daartoe herleidbaar zijn, te laten aanpassen. U kunt een verzoek met die strekking doen aan onze contactpersoon voor privacyzaken. U ontvangt dan binnen 30 dagen een reactie op uw verzoek. Als uw verzoek wordt ingewilligd sturen wij u op het bij ons bekende e-mailadres een bevestiging dat de gegevens zijn aangepast.</p><p><br></p><h5><strong>Recht op beperking van de verwerking</strong></h5><p><br></p><p>U heeft altijd het recht om de gegevens die wij (laten) verwerken die betrekking hebben op uw persoon of daartoe herleidbaar zijn, te beperken. U kunt een verzoek met die strekking doen aan onze contactpersoon voor privacyzaken. U ontvangt dan binnen 30 dagen een reactie op uw verzoek. Als uw verzoek wordt ingewilligd sturen wij u op het bij ons bekende e-mailadres een bevestiging dat de gegevens tot u de beperking opheft niet langer worden verwerkt.</p><p><br></p><h5><strong>Recht op overdraagbaarheid</strong></h5><p><br></p><p>U heeft altijd het recht om de gegevens die wij (laten) verwerken en die betrekking hebben op uw persoon of daartoe herleidbaar zijn, door een andere partij te laten uitvoeren. U kunt een verzoek met die strekking doen aan onze contactpersoon voor privacyzaken. U ontvangt dan binnen 30 dagen een reactie op uw verzoek. Als uw verzoek wordt ingewilligd sturen wij u op het bij ons bekende e-mailadres afschriften of kopieen van alle gegevens over u die wij hebben verwerkt of in opdracht van ons door andere verwerkers of derden zijn verwerkt. Naar alle waarschijnlijkheid kunnen wij in een dergelijk geval de dienstverlening niet langer voortzetten, omdat de veilige koppeling van databestanden dan niet langer kan worden gegarandeerd.</p><p><br></p><h5><strong>Recht van bezwaar en overige rechten</strong></h5><p><br></p><p>U heeft in voorkomende gevallen het recht bezwaar te maken tegen de verwerking van uw persoonsgegevens door of in opdracht van MSSTYLING/HUUSHINNE Als u bezwaar maakt zullen wij onmiddellijk de gegevensverwerking staken in afwachting van de afhandeling van uw bezwaar. Is uw bezwaar gegrond dat zullen wij afschriften en/of kopieen van gegevens die wij (laten) verwerken aan u ter beschikking stellen en daarna de verwerking blijvend staken. U heeft bovendien het recht om niet aan geautomatiseerde individuele besluitvorming of profiling te worden onderworpen. Wij verwerken uw gegevens niet op zodanige wijze dat dit recht van toepassing is. Bent u van mening dat dit wel zo is, neem dan contact op met onze contactpersoon voor privacyzaken.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong><u>Wijzigingen in het privacybeleid</u></strong></h5><p><br></p><p><strong>Wij behouden te allen tijde het recht ons privacybeleid te wijzigen. Op deze pagina vindt u echter altijd de meest recente versie. Als het nieuwe privacybeleid gevolgen heeft voor de wijze waarop wij reeds verzamelde gegevens met betrekking tot u verwerken, dan brengen wij u daarvan per e-mail op de hoogte.</strong></p><p><br></p><p><br></p><p><br></p><p><br></p><p><strong>ï»¿</strong></p>', 8),
	(7, 'Contact', '<p><br></p><p>Heeft u vragen, opmerkingen of heeft u problemen ondervonden op onze site?</p><p><br></p><p>U kunt ons altijd bereiken per e-mail. We streven ernaar om dan uw mail nog dezelfde dag te beantwoorden. Ook zijn we telefonisch bereikbaar van dinsdag tot zaterdag tussen 10:00 en 16:00 uur.</p><p><br></p><p>E-mail: <a href="mailto:info@huushinne.nl" target="_blank" style="background-color: rgb(255, 255, 255);">inf</a><a href="mailto:info@huushinne.nl" target="_blank">o@huushinne.nl</a></p><p><a href="mailto:info@huushinne.nl" target="_blank">Telefoon</a>nummer: 0591-547631 (Lokaal tarief)</p><p>Whatsapp: 0647396824</p><p><br></p><p><span style="background-color: rgb(255, 255, 255);">Mocht u in de omgeving van Emmen zijn, dan bent u ook altijd welkom om alle producten te bewonderne en te passen in </span><a href="/Onze Winkel" target="_blank" style="background-color: rgb(255, 255, 255);">onze winkel</a>.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Bedrijfsgegevens</strong></h5><p><br></p><p>HUUSHINNE</p><p>Dalipassage 2</p><p>7811DB EMMEN</p><p>0591-547631</p><p><br></p><p>Handelsnaam: MSSTYLING</p><p>K.v.K. nummer: 61545988</p><p>BTW-nummer: NL 854384777B01</p><p><br></p><p><br></p><p><br></p>', 2),
	(8, 'Onze Winkel', '<p><br></p><h5><strong>Onze winkel</strong></h5><p><br></p><p>In hartje Emmen is sinds 2014 lifestylestore HUUSHINNE te vinden.</p><p><br></p><p>Wij geloven in eerlijke pure producten die duurzaam geproduceerd zijn.</p><p><br></p><p>In onze winkel verkopen we Scandinavische en Nederlandse woonmerken. Je vind bij ons een mooie collectie serviezen, kussens, plaids, vazen en nog veel meer van o.a. HKliving, Broste Copenhagen, Householdhardware, Via Martine, House Doctor en Malagoon,</p><p><br></p><p>Daarnaast hebben we een stoere modecollectie.in Scandinavische stijl.</p><p>Mooie aardetinten kleuren de collecties van JCSophie en Kaffe.</p><p><br></p><p>We hopen je te mogen begroeten in onze winkel.</p><p><br></p><p>Marja en Ferdi</p><p><br></p><p><img src="https://huushinne.nl/src/images/Huushinne winkelfoto\'s-0033.jpg"></p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Openingstijden</strong></h5><p><br></p><p>Maandag: Gesloten</p><p>Dinsdag: 10:00-17:30 uur</p><p>Woensdag: 10:00-17:30 uur</p><p>Donderdag: 10:00-17:30 uur</p><p>Vrijdag: 10:00-17:30 uur</p><p>Zaterdag: 10:00-17:00 uur</p><p>Zondag: Gesloten</p><p><br></p><h5><strong>Adres</strong></h5><p><br></p><p><br></p><p>HUUSHINNE</p><p>Dalipassage 2</p><p>7811DB EMMEN</p><p><br></p><p><a href="/Bezorgen of Afhalen" target="_blank">Klik hier</a> voor parkeer informatie.</p><p><br></p><iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1206.5627178068858!2d6.892362358330278!3d52.784046217222894!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47b7e63e549977a5%3A0xb17ffcf0bc94d579!2sDalipassage%202%2C%207811%20DB%20Emmen!5e0!3m2!1sen!2snl!4v1614776936754!5m2!1sen!2snl" height="450" width="600"></iframe><p><br></p><p><br></p><p><br></p><p><img src="https://huushinne.nl/src/images/Huushinne 27-07-2022-039.jpg"></p><p><br></p><p><br></p>', 14),
	(9, 'Bezorgen of Afhalen', '<p><br></p><p>Wanneer u op dinsdag - vrijdag vÃ³Ã³r 17:00 uur besteld, wordt uw bestelling dezelfde dag nog door ons verzonden.</p><p>Bestellingen gedaan op zaterdag, zondag en maandag worden de dinsdag erna verzonden.</p><p><br></p><p>Wij verzenden via PostNL. Dit betekent ook dat zodra uw bestelling verzonden is, wij geen invloed meer hebben op de levertijd.</p><p>Voor meer info over levertijden en/of vertragingen verwijzen we u door naar de site van <a href="https://www.postnl.nl" target="_blank">PostNL</a>.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Nederland</strong></h5><p><br></p><p>De standaard verzendkosten zijn â‚¬4,95.</p><p>De levertijd is standaard 1-2 werkdagen, maar houdt u ook rekening met weekenden, feestdagen en vertragingen.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>BelgiÃ«</strong></h5><p><br></p><p>De standaard verzendkosten zijn â‚¬6,95.</p><p>De levertijd is standaard 2-3 werkdagen, maar houdt u ook rekening met weekenden, feestdagen en vertragingen.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Overige Landen</strong></h5><p><br></p><p>We leveren alleen binnen Nederland en naar BelgiÃ«.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Verzenden als cadeau</strong></h5><p><br></p><p>Het is ook mogelijk om uw bestelling in cadeauverpakking te laten bezorgen. Tijdens het afrekenen kunt u hier voor kiezen wanneer u uw verzendmethode kiest.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Verzenden naar een ander adres</strong></h5><p><br></p><p>Het is ook mogelijk om uw bestelling naar een ander adres te versturen dan uw factuur adres. Tijdens het afrekenen kunt u onder uw factuur adres een ander verzend adres invullen.</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Afhalen</strong></h5><p><br></p><p>Bent u woonachtig in de omgeving van Emmen of bent u toevallig in de buurt? Het is namelijk ook mogelijk om uw bestelling gratis af te halen in <a href="/Onze%20Winkel" target="_blank">onze winkel</a>!</p><p><br></p><h5><strong>Adres</strong></h5><p><br></p><p>HUUSHINNE</p><p>Dalipassage 2</p><p>7811DA Emmen</p><p><br></p><h5><strong>Openingstijden</strong></h5><p><br></p><p>Maandag: Gesloten</p><p>Dinsdag: 10:00-17:30 uur</p><p>Woensdag: 10:00-17:30 uur</p><p>Donderdag: 10:00-17:30 uur</p><p>Vrijdag: 10:00-17:30 uur</p><p>Zaterdag: 10:00-17:00 uur</p><p>Zondag: gesloten</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Parkeren</strong></h5><p><br></p><p>De dichtstbijzijnde parkeerplaats is <a href="https://www.centrumparkeren.nl/emmen/parkeergarages/myriade" target="_blank">parkeergarage Myriade</a>.</p><p><br></p><p>Parkeergarage Willinkplein</p><p>Willinkplein 7</p><p>7811DC Emmen</p><p><br></p><iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1206.6192317186787!2d6.893272!3d52.782008!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x7aef3d34c3a650!2sMyriade!5e0!3m2!1snl!2snl!4v1567179847441!5m2!1snl!2snl" height="450" width="600"></iframe><p><br></p><p>Voor meer informatie kunt ook terecht bij onze <a href="/Algemene%20Voorwaarden" target="_blank">Algemene Voorwaarden</a>.</p><p><br></p>', 3),
	(10, 'Retourneren en Ruilen', '<p><br></p><h5><strong>Retourneer Voorwaarden</strong></h5><p><br></p><ul><li>U heeft het recht uw bestelling tot <strong>14 dagen</strong> na ontvangst zonder opgave van reden te annuleren. U heeft <strong>na </strong>annulering<strong> 14 dagen </strong>om uw product retour te sturen.De kosten hiervoor zijn voor eigen rekening.</li><li>U krijgt dan binnen 14 dagen na uw retourneer melding het volledige orderbedrag inclusief verzendkosten teruggestort.Â </li><li>Indien u gebruik maakt van uw herroepingsrecht, zal het product in ongebruikte staat met alle geleverde toebehoren en - indien redelijkerwijze mogelijk - in de originele verpakking aan ons geretourneerd worden.Â </li><li>De verzendkosten voor retourneren en ruilen zijn voor eigen rekening van de klant.</li></ul><p><br></p><p>Om gebruik te maken van dit recht kunt u onderstaande formulier invullen en retourneren via <a href="mailto:info@robertherdermessen.nl" target="_blank">info@huushinne.nl</a>.</p><p><br></p><p><a href="/src/Huushinne.nl Retourformulier.pdf" target="_blank">Retourformulier</a></p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Uitzonderingen</strong></h5><p><br></p><p>Artikelen die door ons apart zijn besteld of aangepast na aanleiding van de wensen van de klant kunnen niet worden geretourneerd.Â </p><p><br></p><p>Bijvoorbeeld:</p><ul><li>Een artikel die niet in de standaard collectie zit en op speciaal verzoek van de klant is besteld.</li><li>Artikelen die zijn voorzien van persoonlijke opschriften.Â </li></ul><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Ruilen</strong></h5><p><br></p><ul><li>U heeft ook het recht uw bestelling tot <strong>14 dagen </strong>na ontvangst zonder opgave van reden te ruilen. U heeft <strong>na </strong>de melding <strong>14 dagen om het product </strong>retour te sturen.</li><li>Nadat we het product/de producten hebben ontvangen, zullen we zo snel mogelijk het besproken vervangend product naar u verzenden.</li></ul><p><br></p><p>Als u graag uw product(en) zou willen ruilen, neem dan alstublieft <a href="/info@huushinne.nl" target="_blank">contact</a> met ons op.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Voor verdere vragen of problemen kunt u uiteraard <a href="info@huushinne.nl" target="_blank">contact</a> met ons opnemen.</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>', 11),
	(11, 'Garantie', '<p><br></p><p>Op onze producten wordt standaard een garantie van 2 jaar gegeven. Deze garantie geldt op materiaalfouten en fabricagefouten bij normaal gebruik met het product.</p><p><br></p><p>---------------------------------------------------------------------------------</p><p><br></p><h5><strong>Uitzonderingen</strong></h5><p><br></p><p>De garantie geldt niet bij:</p><p><br></p><ul><li>Beschadigingen, verkleuringen en gebruikssporen als gevolg van slijtage.</li></ul><p><br></p><p><br></p><p><br></p>', 12),
	(12, 'FAQ', '<p><br></p><h5><strong>Bestellen</strong></h5><p><strong style="font-size: 16px;"><em><u>ï»¿</u></em></strong></p><p><br></p><h5><em><u>Kan ik mijn bestelling wijzigen?</u></em></h5><p><em><u>ï»¿</u></em></p><p>Als u uw bestelling wilt wijzigen voordat het verzonden is neem dan zo snel mogelijk <a href="/Contact " target="_blank">contact </a>met ons op!</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Verzenden & bezorgen</strong></h5><p><br></p><h5><em><u>Ik heb mijn bestelling nog niet ontvangen?</u></em></h5><p><br></p><p>Bekijk eerst alstublieft <a href="/Bezorgen" target="_blank">deze pagina</a>.</p><p><br></p><p>Mocht uw bestelling toch significant lang op zich laten wachten (Nederland 1 week; BelgiÃ« 2 weken), neem dan gerust <a href="/Contact" target="_blank">contact</a> met on op.</p><p><br></p><h5><em><u>Mijn bestelling klopt niet!</u></em></h5><p><br></p><p>Heeft u een incomplete bestelling of andere producten ontvangen? Neem dan zo snel mogelijk <a href="/Contact" target="_blank">contact</a> met ons op!</p><p><br></p><p>----------------------------------------------</p><p><br></p><h5><strong>Account</strong></h5><p><br></p><h5><em><u>Hoe wijzig ik mijn gegevens?</u></em></h5><p><br></p><ul><li>Bovenaan de website kunt u "Mijn account" aanklikken. Als u ingelogd bent gaat u dan naar uw account menu.</li><li>In het menu onder "Mijn account" moet uw klikken op "Gegevens wijzigen".</li><li>U komt nu op een pagina met uw gegevens, hier kunt u ze aanpassen. Vergeet niet op "Verstuur" te klikken op uw wijzigingen op te slaan.</li></ul><p><br></p><h5><em><u>Hoe wijzig ik mijn e-mailadres?</u></em></h5><p><br></p><ul><li>Bovenaan de website kunt u "Mijn account" aanklikken. Als u ingelogd bent gaat u dan naar uw account menu.</li><li>In het menu onder "Mijn account" moet uw klikken op "E-mail wijzigen".</li><li>U komt nu op een pagina waar u uw oude e-mailadres kunt veranderen naar een nieuwe. Vergeet niet op "Verstuur" te klikken op uw wijziging op te slaan.</li></ul><p><br></p><h5><em><u>Hoe wijzig ik mijn wachtwoord?</u></em></h5><p><br></p><ul><li>Bovenaan de website kunt u "Mijn account" aanklikken. Als u ingelogd bent gaat u dan naar uw account menu.</li><li>In het menu onder "Mijn account" moet uw klikken op "Wachtwoord wijzigen".</li><li>U komt nu op een pagina waar u uw oude wachtwoord kunt veranderen naar een nieuwe. Vergeet niet op "Verstuur" te klikken op uw wijziging op te slaan.</li></ul><p><br></p><h5><em><u>Hoe krijg ik een nieuw wachtwoord als ik de oude vergeten of kwijt ben?</u></em></h5><p><br></p><ul><li>Wanneer u probeert in te loggen, maar u bent uw wachtwoord vergeten of kwijt, moet u klikken op "Wachtwoord vergeten?".</li><li>Vervolgens komt u op een pagina waarop u uw e-mailadres dat verbonden is aan uw account moet invullen. Klikt hierna op "Verstuur".</li><li>Nu zult u een e-mail ontvangen met daarin instructies en een link. U moet op deze link klikken.</li><li>Er zal een nieuwe pagina openen waar u een nieuw wachtwoord kan invullen. U moet twee keer hetzelfde nieuwe wachtwoord invullen.</li><li>Als u dit heeft gedaan moet u klikken op "Verstuur". Vanaf nu kunt u weer inloggen met het nieuwe wachtwoord.</li></ul><p><br></p><h5><em><u>Hoe vraag ik een nieuw wachtwoord aan als ik de oude vergeten of kwijt ben en ik ook geen toegang heb het mijn e-mailaccount?</u></em></h5><p><br></p><p>Wanneer u probeert in te loggen, maar u bent uw wachtwoord vergeten of kwijt en u heeft geen toegang meer tot uw e-mailaccount, neem dan gerust <a href="/Contact" target="_blank">contact</a> met ons op. We zullen u dan zo snel mogelijk verder helpen.</p><p><br></p><h5><em><u>Zijn mijn persoonlijke gegevens goed beveiligd?</u></em></h5><p><br></p><p>Ja, tijdens het aanmaken van een account en het plaatsen van een bestelling worden uw gegevens versleuteld en via een beveiligde verbinding (SSL) naar ons verzonden. Uw gegevens kunnen tijdens de overdracht over het internet niet worden gelezen door andere personen omdat het versleuteld is met een soort code. Hiermee bieden wij u veiligheid tijdens de overdracht van uw gegevens tegen diefstal of misbruik via het internet. Deze beveiligde verbinding is te herkennen aan het slotje in de adresbalk links bovenaan uw scherm. <a href="/Privacy Verklaring" target="_blank">Klik hier</a> voor meer informatie.</p><p><br></p><h5><em><u>Hoe kan ik mijn account verwijderen?</u></em></h5><p><br></p><p>Neem in dit geval alstublieft <a href="/Contact" target="_blank">contact</a> met ons op. We zullen vervolgens binnen 1-3 werkdagen uw account verwijderen en u via de mail hiervan op de hoogte stellen. Het is ook mogelijk om al uw gegevens op te vragen als uw dat wenst.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Neem bij verdere vragen gerust <a href="/Contact" target="_blank">contact</a> met ons op!</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>', 15),
	(13, 'Algemene Voorwaarden', '<p>Huushinne.nl is een handelsnaam van MSSTYLING, ingeschreven in het Handelsregister onder nummer 61545988.</p><p><br></p><p><br></p><p><br></p><p>Algemeen</p><p><br></p><p><br></p><p>â€¢	Deze Algemene Voorwaarden zijn van toepassing op alle aanbiedingen, bestellingen en overeenkomsten van Huushinne.nl met haar klanten, de kopers van haar producten via het internet. Voor levering aan niet- consumenten gelden andere voorwaarden. Deze zijn op te vragen bij de Klantenservice via info@huushinne.nl en wordt verstrekt bij offertes.</p><p>â€¢	Door het gebruik van de internetsite: info@huushinne.nl en/of een bestelling te plaatsen verklaart de klant akkoord te gaan met deze Algemene Voorwaarden.</p><p>â€¢	Op verzoek van de klant zullen deze voorwaarden per e-mail of per post toegezonden worden.</p><p>â€¢	Eventuele (inkoop)voorwaarden van de klant worden uitdrukkelijk van de hand gewezen. Van deze Algemene Voorwaarden kan alleen schriftelijk worden afgeweken. In dat geval blijven alle overige bepalingen van deze Voorwaarden van kracht. Alle rechten en aanspraken, zoals in deze Algemene Voorwaarden en in eventuele nadere overeenkomsten ten behoeve van Huushinne.nl worden bedongen, worden evenzeer bedongen ten behoeve van door Huushinne.nl ingeschakelde tussenpersonen en andere derden.</p><p><br></p><p>Indien door een gerechtelijke uitspraak of door een bindende uitspraak van een andere bevoegde instantie Ã©Ã©n van de artikelen van deze Voorwaarden ongeldig wordt verklaard, blijven de overige bepalingen van deze Voorwaarden in stand.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Totstandkoming</p><p><br></p><p>â€¢	Alle aanbiedingen van Huushinne.nl zijn vrijblijvend.</p><p>â€¢	Bestellingen kunnen met een volledig ingevuld bestelformulier via de website van Huushinne.nl worden geplaatst.</p><p>â€¢	Een overeenkomst komt tot stand op het moment dat een order bevestiging door Huushinne.nl via de internetsite info@huushinne.nl is verstuurd naar de klant. Huushinne.nl houdt zich het recht voor bestellingen te weigeren dan wel aanvullende informatie op te vragen zonder opgave van reden. Huushinne.nl levert niet aan wederverkopers.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Prijzen en betalingen</p><p><br></p><p>â€¢	De vermelde prijzen op info@huushinne.nl voor de aangeboden artikelen en diensten zijn in euro\'s, inclusief BTW en exclusief handelings- en verzendkosten, eventuele belastingen of andere heffingen, tenzij anders vermeld of schriftelijk overeengekomen.</p><p>â€¢	De prijzen op deze site zijn onder voorbehoud van wijzigingen ongeacht de reden hiervan.</p><p>â€¢	De klant dient te betalen door gebruik te maken van de betaalmethoden - aangeboden tijdens het bestelproces. Aan deze bestelling kunnen nadere (betalings- /bestel- )voorwaarden worden gesteld. Bij betaling per bank of giro geldt als datum van betaling de datum van creditering van de bankrekening van Huushinne.nl.</p><p>â€¢	De klant geeft Huushinne.nl toestemming alle handelingen te verrichten die nodig zijn om betaling te laten plaatsvinden op de door de klant gekozen betalingswijze.</p><p>â€¢	Huushinne.nl kan niet gehouden worden aan prijsvermeldingen die evident onjuist zijn, bijvoorbeeld als gevolg van kennelijke fouten in lay-out of typewerk. Aan onrechtmatige prijsinformatie kunnen geen rechten worden ontleend.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Levering</p><p><br></p><p>â€¢	De door Huushinne.nl genoemde (leverings-) termijnen worden bij benadering gegeven en zijn vastgesteld op grond van de gegevens en omstandigheden die bij het aangaan van de overeenkomst aan Huushinne.nl bekend waren. Opgegeven leveringstermijnen zullen nimmer zijn te beschouwen als een fatale termijn.</p><p>â€¢	Indien een wijziging in de gegevens en/of omstandigheden, ongeacht de voorzienbaarheid daarvan, vertraging tot gevolg heeft, wordt de leveringsdatum dienovereenkomstig verlaat. Bij niet tijdige levering dient Huushinne.nl schriftelijk in gebreke te worden gesteld, waarbij haar nog een redelijke termijn tot levering moet worden geboden.</p><p>â€¢	Overschrijding van de door Huushinne.nl opgegeven leveringstermijnen, door welke oorzaak dan ook, geeft de klant nimmer recht op schadevergoeding of niet- nakoming van enige op hem rustende verplichting uit de desbetreffende overeenkomst dan wel een daarmee samenhangende overeenkomst.</p><p>â€¢	Bij overschrijding van de bij benadering gegeven levertijd met meer dan 30 dagen heeft de klant het recht de overeenkomst kosteloos te ontbinden. Hiervoor kan de klant het retourformulier downloaden en deze ingevuld retourneren via info@huushinne.nl. Eventuele betalingen worden in dat geval binnen 14 dagen na de kennisgeving aan de klant geretourneerd.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Verzending</p><p><br></p><p>â€¢	Huushinne.nl verzendt de bestelde artikelen per PostNL naar een adres in Nederland en BelgiÃ« welke is opgegeven door de klant. Huushinne.nl verstuurt niet naar postbussen. Huushinne.nl verzend zowel per brievenbuspakje als per pakket.</p><p>â€¢	In geval dat een pakket niet bij de klant kan worden aangeboden, wordt het pakket bij de buren bezorgd. Indien dit niet mogelijk is laat de bezorger een bericht bij de klant achter. Mocht de klant dan ook niet thuis zijn dan krijgt de klant een bericht bij welk dichtbij zijnde postkantoor het pakket is af te halen door de klant. Deze heeft dan nog drie weken de tijd om het pakket af te halen. Indien de periode waarin de klant het pakket af kan halen verstreken is, wordt het pakket automatisch teruggezonden naar Huushinne.nl.</p><p>â€¢	Wil de klant na deze periode het pakket verstuurd hebben, dan worden er extra administratie- en verzendkosten in rekening gebracht welke vooruit betaald dienen te worden.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Belangrijke informatie over de artikelen</p><p><br></p><p>â€¢	Huushinne.nl zal er voor zorgen dat de foto\'s op deze website zo veel mogelijk actueelÂ zijn.</p><p>----------------------------------------------</p><p><br></p><p>Garantie</p><p><br></p><p>â€¢	Op onze producten wordt standaard een garantie van 2 jaar gegeven. Deze garantie geldt op materiaalfouten en fabricagefouten bij normaal gebruik met het product.</p><p>â€¢	Uitgezonderd hiervan zijn beschadigingen, verkleuringen en gebruikssporen als gevolg van slijtage.</p><p>----------------------------------------------</p><p><br></p><p>Controle en reclameren</p><p><br></p><p>â€¢	Het geleverde product dient direct na ontvangst door de klant gecontroleerd te worden op volledigheid en op zichtbare gebreken. Kleine oneffenheden en afwijkingen in kleur en vorm gelden niet als gebrek, aangezien het hier om ambachtelijk gemaakte artikelenÂ gaat uit natuurlijke materialen.</p><p>â€¢	Mocht Huushinne.nl het verkeerde of een beschadigd artikel aan de klant hebben gestuurd dan zal het artikel vervangen worden zonder extra kosten daar voor te rekenen. De klant dient wel binnen 5 dagen na ontvangst Huushinne.nl per e-mail via info@huushinne.nl op de hoogte hiervan te stellen. Na het verstrijken van deze periode gaat Huushinne.nl ervan uit dat de klant het artikel heeft geaccepteerd.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Herroepingsrecht</p><p><br></p><p>â€¢	Mocht de klant, om welke reden dan ook, ervoor kiezen het product niet te houden, dan heeft deze het recht om het te ruilen of te retourneren gedurende 14 dagen. Deze bedenktermijn gaat in op de dag na ontvangst van het product door de consument. Het aankoopbedrag wordt dan binnen 14 dagen na de melding van de retourzending door Huushinne.nl terugbetaald.</p><p>â€¢	Om gebruik te maken van dit recht moet de klant het retourformulier downloaden en ingevuld opsturen per e-mail via info@huushinne.nl.</p><p>â€¢	De klant dient binnen 14 dagen na melding het ongebruikte product met alle geleverde toebehoren en - indien redelijkerwijze mogelijk - in de originele staat en verpakking aan Huushinne.nl te retourneren aan het volgende adres:</p><p><br></p><p>HUUSHINNE</p><p>Dalipassage 2</p><p>7811DB EMMEN</p><p><br></p><p>â€¢	De retourzending is voor eigen rekening van de klant.. Tot ontvangst van de goederen bij Huushinne.nl blijft de klant verantwoordelijk voor deze goederen.</p><p>â€¢	Geretourneerde producten worden alleen geaccepteerd wanneer het onbeschadigd met alle geleverde toebehoren en - indien redelijkerwijze mogelijk - in de originele verpakking aan ons geretourneerd wordt. Beschadigde, gebruikte, bevuilde en onjuist gefrankeerde producten worden niet geaccepteerd.</p><p>----------------------------------------------</p><p><br></p><p>Aansprakelijkheid/Overmacht</p><p><br></p><p>â€¢	Huushinne.nl is niet aansprakelijk voor misverstaan, beschadigingen, vertragingen of niet behoorlijk overkomen van bestellingen en mededelingen als gevolg van gebruik van internet of andere communicatiemiddelen tussen klant en Huushinne.nl, dan wel tussen Huushinne.nl en derden, tenzij er sprake is van opzet of grove schuld van Huushinne.nl.</p><p>â€¢	Indien nakoming onmogelijk is doordat het bestelde artikel niet beschikbaar is, zal Huushinne.nl de klant daarvan zo spoedig mogelijk kennis geven en heeft de klant recht op kosteloze teruggave van het door hem aan Huushinne.nl betaalde bedrag. De teruggave zal zo spoedig mogelijk en in ieder geval binnen dertig dagen na de kennisgeving plaatsvinden.</p><p>â€¢	Huushinne.nl is niet verantwoordelijk wanneer er een foutief afleveradres is opgegeven door de klant.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Klachten Regeling</p><p><br></p><p>Bij klachten dient een consument zich allereerst te wenden tot de ondernemer. Daarna kunt u terecht bij het keurmerk WebwinkelKeur. Bij klachten die vervolgens nog niet opgelost kunnen worden dient de consument zich te wenden tot het Europees ODR platform.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Recht van toepassing</p><p><br></p><p>Alle overeenkomsten vallen onder het Nederlands Recht. Alle geschillen zullen worden voorgelegd aan de Nederlandse rechtbank welke jurisprudentie voor handen heeft.</p><p>Voor op/aanmerkingen, suggesties en geschillen kunt u contact opnemen door een e-mail te sturen naar info@huushinne.nl.</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><h5><br></h5><h5><br></h5><h5><br></h5><h5><br></h5><p><br></p>', 0),
	(15, 'Klachten', '<p><br></p><p>Heeft u een klacht over een product, onze service, etc. dan verzoeken we u om eerst met ons <a href="/Contact" target="_blank">contact</a> op te nemen. We nemen uw klacht dan zo snel mogelijk in behandeling en kunnen het zo hopelijk samen met uw oplossen.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Komen we er samen niet uit, dan kunt u hierna uw klacht kwijt bij het keurmerk <a href="https://www.webwinkelkeur.nl/consument/#" target="_blank">WebwinkelKeur</a>.</p><p><br></p><p>----------------------------------------------</p><p><br></p><p>Leidt dit alles helaas niet tot een oplossing?</p><p><br></p><p>Als consument wonend in de EU kunt u uw klachten melden aan het <a href="https://ec.europa.eu/consumers/odr/main/index.cfm?event=main.home.chooseLanguage" target="_blank">ODR</a> platform van de Europese Commissie.</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>', 10),
	(22, 'Klantenservice', '<p><br></p><p>Heeft u vragen, opmerkingen of heeft u problemen ondervonden op onze site?</p><p><br></p><p>U kunt ons altijd bereiken per e-mail. We streven ernaar om uw mail nog dezelfde dag te beantwoorden. Ook zijn we telefonisch bereikbaar van dinsdag tot zaterdag tussen 10:00 en 16:00 uur.</p><p><br></p><p>E-mail: <a href="mailto:info@robertherdermessen.nl" target="_blank" style="background-color: rgb(255, 255, 255);">info@huushinne.nl</a></p><p>Telefoonnummer: 0591-547631 (Lokaal tarief)</p><p>Whatsapp: 0647396824</p><p><br></p><p><span style="background-color: rgb(255, 255, 255);">Mocht u in de omgeving van Emmen zijn, dan bent u ook altijd welkom om alle producten te bewonderen en passen in </span><a href="/Onze Winkel" target="_blank" style="background-color: rgb(255, 255, 255);">onze winkel</a>.</p><p><br></p><p><br></p><p><br></p><p><br></p>', 1);

-- Dumping structure for table db3749273_thuisbijdekat.sessions
CREATE TABLE IF NOT EXISTS `sessions` (
  `id` varchar(250) NOT NULL,
  `access` int(10) unsigned DEFAULT NULL,
  `data` longtext DEFAULT NULL,
  `ip` varchar(200) DEFAULT NULL,
  `request_uri` varchar(800) DEFAULT NULL,
  `last_action` varchar(200) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table db3749273_thuisbijdekat.sessions: ~0 rows (approximately)

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
